---
- name: Check for required vars
  fail:
    msg: "Please specify a value for {{ item }}"
  when: item is undefined
  with_items:
  - osoan_cluster_name
  - osoan_woopra_enabled
  - osoan_woopra_domain

- include: uninstall.yml
  when: osoan_uninstall | bool

# When this role was introduced, we renamed the various objects in OpenShift to better
# align with all our other apps. (renamed from online-user-analytics to just analytics)
# Make sure we clear out the old objects if we see them even if uninstall was not set.
# Because this app is stateless in the cluster, no data should be lost here, we just
# resume submitting to Woopra.
# TODO: this can be removed once this role has run against all environments
# TODO: why does this always show a change?
- name: Uninstall legacy components
  oc_obj:
    state: absent
    kind: "{{ item.kind }}"
    name: "{{ item.name }}"
    namespace: "{{ osoan_namespace }}"
  with_items:
    - { kind: "deploymentconfig", name: "online-user-analytics" }

- debug: msg="Deploying {{ osoan_name}} from {{ osoan_git_repo }} ref {{osoan_git_ref }}"

- name: Copy application template
  copy:
    src: analytics-template.yaml
    dest: "{{ osoan_template_path }}"
    #  register: copy_template_out

- name: Create template
  oc_obj:
    state: present
    namespace: "{{ osoan_namespace }}"
    name: user-analytics
    kind: template
    files:
    - "{{ osoan_template_path }}"

- name: Apply template
  shell: "oc process -n {{ osoan_namespace }} user-analytics -p GIT_REPO='{{ osoan_git_repo }}' -p GIT_REF='{{ osoan_git_ref }}' -p WOOPRA_ENABLED='{{ osoan_woopra_enabled }}' -p WOOPRA_ENDPOINT='{{ osoan_woopra_endpoint }}' -p WOOPRA_DOMAIN='{{ osoan_woopra_domain }}' -p LOCAL_ENDPOINT_ENABLED='{{ osoan_local_endpoint_enabled }}' -p USER_KEY_STRATEGY='{{ osoan_user_key_strategy }}' -p CLUSTER_NAME='{{ osoan_cluster_name }}' -p LOG_LEVEL='{{ osoan_log_level }}' | oc apply -n {{ osoan_namespace }} -f -"
  # apply does not indicate if something changed today. Assume changed_when
  # false and rely on the template update as our best indicator if something
  # changed.
  changed_when: false

- name: Fetch latest git commit
  git:
    repo: "{{ osoan_git_repo }}"
    version: "{{ osoan_git_ref }}"
    clone: no
    accept_hostkey: true
  register: git_sha1_results
  # Git may not be installed on remote hosts.
  delegate_to: localhost
  changed_when: false

- debug: msg="Checking that latest build matches git ref {{ git_sha1_results.after }}"

- name: Start build if required
  oc_start_build_check:
    namespace: "{{ osoan_namespace }}"
    buildconfig: "analytics"
    git_ref: "{{ git_sha1_results.after }}"
  register: start_build_out

- debug: var=start_build_out


