---
- name: "uninstall all {{ osoan_name }} components"
  oc_obj:
    state: absent
    kind: "{{ item.kind }}"
    name: "{{ item.name }}"
    namespace: "{{ osoan_namespace }}"
  with_items:
    - { kind: "buildconfig", name: "{{ osoan_name }}" }
    - { kind: "deploymentconfig", name: "{{ osoan_name }}" }
    - { kind: "imagestream", name: "{{ osoan_name }}" }
    - { kind: "clusterrolebinding", name: "{{ osoan_name }}" }
    - { kind: "clusterrole", name: "{{ osoan_name }}" }
    - { kind: "serviceaccount", name: "{{ osoan_name }}" }
    - { kind: "service", name: "{{ osoan_name }}" }
- name: "remove {{ osoan_template_path }}"
  file:
    path: "{{ osoan_template_path }}"
    state: absent
