---
output_dir: ./
repos:
- id: openshift-ansible
  url: https://github.com/openshift/openshift-ansible.git
  version: openshift-ansible-3.7.0-0.125.0

  copy:
  - src: roles/lib_openshift/
    dst: roles/lib_openshift/
- id: online-archivist
  url: https://github.com/openshift/online-archivist.git
  version: master
  copy:
  - src: ansible/roles/oc_start_build_check/
    dst: roles/oc_start_build_check/
